### ISSUE TITLE
safe from esea

### ISSUE THREAD

**Issue by andys608** [Zer0Mem0ry/KernelBhop#5]
Since we're reading, and writing memory from driver and not using winapi. Have you done any esea testing with this source. So will this code bypass esea anti cheat client. Do you have any information on what may trigger a dection. I wanna write a triggerbot using this source for esea.

**Comment by 0daydreamer** [comment]
Sorry but that won't work. First of all DSEFix is detected, and second of all they have a kernel driver and have extensive checks for kernel-mode cheats. If you would've bothered to search on google you would've known that.

**Comment by jakeau** [comment]
I actually just modified a windows driver and I can read and write in esea no issues 1 and a bit years later.

**Comment by zw0pen** [comment]
> Do you have any information on what may trigger a dection

I find it difficult to believe that you aren't able to understand the detection vectors of this simple kernel implementation of a BHOP cheat being re-purposed into a triggerbot and yet you have successfully modified a Windows driver and bypassed ESEA successfully for a 365+ day period.

Just sayin..

**Comment by masnbota** [comment]
> > Do you have any information on what may trigger a dection
> 
> I find it difficult to believe that you aren't able to understand the detection vectors of this simple kernel implementation of a BHOP cheat being re-purposed into a triggerbot and yet you have successfully modified a Windows driver and bypassed ESEA successfully for a 365+ day period.
> 
> Just sayin..

Could you please explain some of the detection vectors of this driver? Obviously except from being sigged, changing it up and rewriting it a bit and getting a certificate, what exactly are some detection vectors? I'm new to kernel development.

**Comment by Zer0Mem0ry** [comment]
> Sorry but that won't work. First of all DSEFix is detected, and second of all they have a kernel driver and have extensive checks for kernel-mode cheats. If you would've bothered to search on google you would've known that.
